In [3]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
len(alphabets)

26

## Preprocess the data

In [8]:
# Dictionary mapping from int to alphabets
int_to_char = {i: alphabet for i, alphabet in enumerate(alphabets)}

# Dictionary mapping from alphabets to int
char_to_int = {alphabet: i for i, alphabet in enumerate(alphabets)}

In [10]:
# Creating a sequence length
seq_length = 1

# Creating the data
X = []
y = []

for i in range(len(alphabets) - seq_length):
    seq_in = [alphabets[i]]
    seq_out = alphabets[i+1]
    X += [[char_to_int[seq_in[0]]]]
    y += [char_to_int[seq_out]]
    # print(seq_in, '->', seq_out)

## One Hot encoding

In [20]:
from keras.utils import to_categorical

y_new = to_categorical(y)
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [21]:
y_new.shape

(25, 26)

In [22]:
import numpy as np

print(np.array(X).shape)
X = np.reshape(X, (25,1,1))
print(X.shape)

(25, 1)
(25, 1, 1)


In [25]:
X

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

## Scaling the data

In [26]:
X = X / 25
X

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

## Build the Model

In [27]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [28]:
model = Sequential()

model.add(Dense(25, input_shape=(1,1), activation='relu'))
model.add(LSTM(128))
model.add(Dense(26, activation='softmax'))

In [29]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [30]:
model.fit(X, y_new, epochs=1000, batch_size=1)

Epoch 1/1000
25/25 [==============================] - 2s 6ms/step - loss: 3.2692 - accuracy: 0.0000e+00
Epoch 2/1000
25/25 [==============================] - 0s 5ms/step - loss: 3.2580 - accuracy: 0.0400
Epoch 3/1000
25/25 [==============================] - 0s 5ms/step - loss: 3.2536 - accuracy: 0.0000e+00
Epoch 4/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.2489 - accuracy: 0.0400
Epoch 5/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.2439 - accuracy: 0.0400
Epoch 6/1000
25/25 [==============================] - 0s 5ms/step - loss: 3.2349 - accuracy: 0.0400
Epoch 7/1000
25/25 [==============================] - 0s 5ms/step - loss: 3.2252 - accuracy: 0.0400
Epoch 8/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.2109 - accuracy: 0.0000e+00
Epoch 9/1000
25/25 [==============================] - 0s 5ms/step - loss: 3.1977 - accuracy: 0.0000e+00
Epoch 10/1000
25/25 [==============================] - 0s 5ms/step - loss: 3.1700 - 

In [31]:
model.evaluate(X, y_new, batch_size=1)

25/25 [==============================] - 1s 3ms/step - loss: 0.4877 - accuracy: 0.9600


[0.48766040802001953, 0.9599999785423279]

## Predict on the new data

In [48]:
new = 'E'
new = char_to_int[new]
new

4

In [49]:
new = new / 25
new

0.16

In [50]:
new = np.array([[[new]]])
new

array([[[0.16]]])

In [51]:
pred_prob = model.predict(new, verbose=0)
pred_prob

array([[3.57104986e-20, 3.15275166e-08, 4.88486620e-08, 2.51853489e-05,
        2.73153372e-02, 9.42270458e-01, 3.03192902e-02, 6.73884351e-05,
        2.10318603e-06, 1.93816206e-07, 1.11838894e-08, 5.33059652e-10,
        2.06071141e-12, 6.21612245e-13, 6.72020152e-14, 6.85208912e-15,
        4.58907204e-16, 1.34656575e-17, 2.68718359e-19, 8.27088120e-21,
        2.97297315e-22, 9.84354127e-24, 2.43336250e-25, 6.49437059e-27,
        3.18229325e-28, 1.75669017e-30]], dtype=float32)

In [52]:
pred = np.argmax(pred_prob)
pred

5

In [53]:
pred_char = int_to_char[pred]
pred_char

'F'