In [1]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
len(alphabets)

26

## Preprocess the data

In [4]:
# Dictionary mapping from int to alphabets
int_to_char = {i: alphabet for i, alphabet in enumerate(alphabets)}

# Dictionary mapping from alphabets to int
char_to_int = {alphabet: i for i, alphabet in enumerate(alphabets)}

In [7]:
# Creating a sequence length
seq_length = 3

# Creating the data
X = []
y = []

for i in range(len(alphabets) - seq_length):
    seq_in = alphabets[i: i+seq_length]
    seq_out = alphabets[i+seq_length]
    X.append([char_to_int[char] for char in seq_in])
    y.append(char_to_int[seq_out])
    # print(seq_in, '->', seq_out)

## One Hot encoding

In [9]:
from keras.utils import to_categorical

y_new = to_categorical(y)
y_new

2023-12-18 11:46:14.952188: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-18 11:46:15.016362: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-18 11:46:15.016394: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-18 11:46:15.017345: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-18 11:46:15.024508: I tensorflow/core/platform/cpu_feature_guar

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [10]:
y_new.shape

(23, 26)

In [13]:
import numpy as np

print(np.array(X).shape)
X = np.reshape(X, (23,3,1))
print(X.shape)

(23, 3)
(23, 3, 1)


In [14]:
X

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[ 9],
        [10],
        [11]],

       [[10],
        [11],
        [12]],

       [[11],
        [12],
        [13]],

       [[12],
        [13],
        [14]],

       [[13],
        [14],
        [15]],

       [[14],
        [15],
        [16]],

       [[15],
        [16],
        [17]],

       [[16],
        [17],
        [18]],

       [[17],
        [18],
        [19]],

       [[18],
        [19],
        [20]],

       [[19],
        [20],
        [21]],

       [[20],
        [21],
        [22]],

       [[21],
        [22],
        [23]],

       [[22],
        [23],
    

## Scaling the data

In [15]:
X = X / 25
X

array([[[0.  ],
        [0.04],
        [0.08]],

       [[0.04],
        [0.08],
        [0.12]],

       [[0.08],
        [0.12],
        [0.16]],

       [[0.12],
        [0.16],
        [0.2 ]],

       [[0.16],
        [0.2 ],
        [0.24]],

       [[0.2 ],
        [0.24],
        [0.28]],

       [[0.24],
        [0.28],
        [0.32]],

       [[0.28],
        [0.32],
        [0.36]],

       [[0.32],
        [0.36],
        [0.4 ]],

       [[0.36],
        [0.4 ],
        [0.44]],

       [[0.4 ],
        [0.44],
        [0.48]],

       [[0.44],
        [0.48],
        [0.52]],

       [[0.48],
        [0.52],
        [0.56]],

       [[0.52],
        [0.56],
        [0.6 ]],

       [[0.56],
        [0.6 ],
        [0.64]],

       [[0.6 ],
        [0.64],
        [0.68]],

       [[0.64],
        [0.68],
        [0.72]],

       [[0.68],
        [0.72],
        [0.76]],

       [[0.72],
        [0.76],
        [0.8 ]],

       [[0.76],
        [0.8 ],
        [0.84]],



## Build the Model

In [16]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [18]:
model = Sequential()

model.add(Dense(25, input_shape=(3,1), activation='relu'))
model.add(LSTM(128))
model.add(Dense(26, activation='softmax'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 3, 25)             50        
                                                                 
 lstm_1 (LSTM)               (None, 128)               78848     
                                                                 
 dense_3 (Dense)             (None, 26)                3354      
                                                                 
Total params: 82252 (321.30 KB)
Trainable params: 82252 (321.30 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [20]:
model.fit(X, y_new, epochs=1000, batch_size=1)

Epoch 1/1000
23/23 [==============================] - 2s 7ms/step - loss: 3.2867 - accuracy: 0.0000e+00
Epoch 2/1000
23/23 [==============================] - 0s 6ms/step - loss: 3.2501 - accuracy: 0.0000e+00
Epoch 3/1000
23/23 [==============================] - 0s 6ms/step - loss: 3.2263 - accuracy: 0.0000e+00
Epoch 4/1000
23/23 [==============================] - 0s 7ms/step - loss: 3.1983 - accuracy: 0.0435
Epoch 5/1000
23/23 [==============================] - 0s 6ms/step - loss: 3.1529 - accuracy: 0.0000e+00
Epoch 6/1000
23/23 [==============================] - 0s 6ms/step - loss: 3.1098 - accuracy: 0.0000e+00
Epoch 7/1000
23/23 [==============================] - 0s 6ms/step - loss: 3.0584 - accuracy: 0.0435
Epoch 8/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.0171 - accuracy: 0.0870
Epoch 9/1000
23/23 [==============================] - 0s 5ms/step - loss: 2.9774 - accuracy: 0.0870
Epoch 10/1000
23/23 [==============================] - 0s 6ms/step - loss: 2.935

In [21]:
model.evaluate(X, y_new, batch_size=1)

23/23 [==============================] - 1s 4ms/step - loss: 0.0428 - accuracy: 1.0000


[0.04283034801483154, 1.0]

## Predict on the new data

In [22]:
new = 'EFG'
new = np.array([char_to_int[char] for char in new])
new

array([4, 5, 6])

In [23]:
new = new / 25
new

array([0.16, 0.2 , 0.24])

In [32]:
new = new.reshape(1, 3, 1)
new

array([[[0.16],
        [0.2 ],
        [0.24]]])

In [33]:
pred_prob = model.predict(new, verbose=0)
pred_prob

array([[8.2182358e-11, 3.7450341e-11, 6.7720864e-11, 1.4115633e-11,
        5.9825588e-08, 2.5117054e-06, 7.2029443e-04, 9.9078417e-01,
        8.1007387e-03, 3.2021725e-04, 7.0394992e-05, 1.3357489e-06,
        9.9181676e-08, 5.5268004e-09, 2.7771275e-08, 4.5770239e-08,
        2.8241274e-09, 3.4149319e-10, 1.0853469e-11, 2.4766562e-08,
        6.3927772e-08, 6.8848521e-10, 2.7029407e-12, 6.4633787e-10,
        1.6551566e-09, 2.7745925e-11]], dtype=float32)

In [34]:
pred = np.argmax(pred_prob)
pred

7

In [35]:
pred_char = int_to_char[pred]
pred_char

'H'