In [112]:
import warnings
import string
import warnings
warnings.filterwarnings('ignore')
import os
import pandas as pd

In [113]:
headlines = []
for filename in os.listdir('./data'):
    if "Article" in filename:
        article_df = pd.read_csv('./data/' + filename)
        headlines.extend(list(article_df['headline'].values))

In [114]:
def clean_text(headline):
  text = "".join(word for word in headline if word not in string.punctuation).lower()
  text = text.encode('utf-8').decode("ascii","ignore")
  return text

corpus = [clean_text(headline) for headline in headlines]

In [115]:
vocab = []
for line in corpus:
    words = line.split()
    for word in words:
        vocab.append(word)
vocabulary = set(vocab)
len(vocabulary)

10778

In [116]:
# !pip install keras_preprocessing

In [117]:
from keras.preprocessing.text import Tokenizer
from keras_preprocessing.sequence import pad_sequences
from keras.utils import to_categorical

In [118]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
word2index = tokenizer.word_index
len(word2index)

10778

In [119]:
index2word = {value:key for key, value in word2index.items()}
index2word

{1: 'the',
 2: 'a',
 3: 'to',
 4: 'of',
 5: 'in',
 6: 'for',
 7: 'and',
 8: 'unknown',
 9: 'on',
 10: 'is',
 11: 'trump',
 12: 'with',
 13: 'new',
 14: 'at',
 15: 'how',
 16: 'what',
 17: 'you',
 18: 'an',
 19: 'from',
 20: 'trumps',
 21: 'as',
 22: 'it',
 23: 'its',
 24: 'are',
 25: 'your',
 26: 'not',
 27: 'be',
 28: 'us',
 29: 'season',
 30: 'that',
 31: 'by',
 32: 'about',
 33: 'but',
 34: 'can',
 35: 'episode',
 36: 'do',
 37: 'york',
 38: 'when',
 39: 'this',
 40: 'up',
 41: 'why',
 42: 'over',
 43: 'no',
 44: 'i',
 45: 'out',
 46: 'more',
 47: 'after',
 48: 'my',
 49: 'will',
 50: 'may',
 51: 'health',
 52: 'we',
 53: 'or',
 54: 'war',
 55: 'who',
 56: 'his',
 57: 'questions',
 58: 'today',
 59: 'president',
 60: 'now',
 61: 'house',
 62: 'teaching',
 63: 'should',
 64: 'get',
 65: 'have',
 66: 'one',
 67: 'was',
 68: 'into',
 69: 'all',
 70: 'dont',
 71: 'home',
 72: 'good',
 73: 'plan',
 74: 'life',
 75: 'our',
 76: 'has',
 77: 'gop',
 78: 'says',
 79: 'first',
 80: 'like',
 8

In [120]:
input_sequence = tokenizer.texts_to_sequences(corpus)
input_sequence

[[2341, 4910, 171, 1827],
 [28, 2342, 327, 383, 6, 112, 136],
 [83, 11, 7, 1, 674, 137, 262],
 [3, 4911, 1074, 105, 1828, 4912, 1829, 7, 3182],
 [2343, 4913, 3, 675, 4914, 47, 3183, 3, 1, 81, 61],
 [105, 2344, 4915, 3, 2345, 82, 1075],
 [59, 20, 4916, 7, 1076, 676, 942, 32, 143, 184, 3, 1077],
 [677, 1078, 355],
 [678, 606, 2346, 5, 18, 1830, 185],
 [1, 842, 4, 943, 944, 35, 124, 2, 843, 127],
 [3184],
 [844, 744, 10, 4917, 31, 20, 4918, 9, 143, 273],
 [10, 106, 1831, 2, 4919, 356, 6, 1, 406, 252, 7, 4920, 6, 106, 99],
 [8],
 [43, 3185, 17, 34, 4921, 25, 3186],
 [1079, 4922],
 [28, 1832, 357, 9, 2347, 55, 4923, 745],
 [2, 4924, 4925, 3187, 1491, 4926, 31, 1, 59],
 [407, 4, 4927, 4928, 1833, 2348, 4, 516, 53, 4929, 4930],
 [4931, 7, 4932, 96, 4933],
 [34, 1834, 27, 1492],
 [1268, 3188, 358, 3189, 12, 1, 845, 945],
 [1, 1493, 1494, 67, 26, 32, 188],
 [1835, 2, 1836, 44, 70, 846, 5],
 [1, 359, 556, 133, 303, 172, 607],
 [1269, 517, 1495],
 [16, 4934, 338, 46, 134, 1837, 4935],
 [8],
 [2, 

In [121]:
input_data = []
target = []

for line in input_sequence:
    for i in range(1, len(line) - 1):
        input_data.append(line[:i])
        target.append(line[i])

In [122]:
len(input_data)

40113

In [123]:
MAX_LEN = 0
for seq in input_data:
    if len(seq) > MAX_LEN:
        MAX_LEN = len(seq)

MAX_LEN

22

In [124]:
input_data = pad_sequences(input_data,maxlen=MAX_LEN,padding='post')
input_data

array([[2341,    0,    0, ...,    0,    0,    0],
       [2341, 4910,    0, ...,    0,    0,    0],
       [  28,    0,    0, ...,    0,    0,    0],
       ...,
       [ 102,    9,    0, ...,    0,    0,    0],
       [ 102,    9, 1039, ...,    0,    0,    0],
       [ 102,    9, 1039, ...,    0,    0,    0]], dtype=int32)

In [125]:
from keras.utils import to_categorical

target = to_categorical(target)

In [126]:
target.shape

(40113, 10779)

In [127]:
from keras.models import Sequential
from keras.layers import Embedding, GRU, Dense, Dropout, LSTM
from keras.callbacks import EarlyStopping
import keras

In [128]:
keras.backend.clear_session()
model = Sequential()

model.add(Embedding(input_dim=len(vocabulary)+1, output_dim=100, input_length=MAX_LEN))
model.add(LSTM(units=100))
model.add(Dropout(rate=0.1))
model.add(Dense(units=target.shape[1], activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 22, 100)           1077900   
                                                                 
 lstm (LSTM)                 (None, 100)               80400     
                                                                 
 dropout (Dropout)           (None, 100)               0         
                                                                 
 dense (Dense)               (None, 10779)             1088679   
                                                                 
Total params: 2246979 (8.57 MB)
Trainable params: 2246979 (8.57 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [129]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [130]:
input_data.shape

(40113, 22)

In [131]:
history = model.fit(input_data, target, batch_size=10, epochs=10)

Epoch 1/10
4012/4012 [==============================] - 104s 25ms/step - loss: 7.6330 - accuracy: 0.0412
Epoch 2/10
4012/4012 [==============================] - 102s 26ms/step - loss: 7.2622 - accuracy: 0.0417
Epoch 3/10
4012/4012 [==============================] - 103s 26ms/step - loss: 7.2127 - accuracy: 0.0418
Epoch 4/10
4012/4012 [==============================] - 101s 25ms/step - loss: 7.1964 - accuracy: 0.0418
Epoch 5/10
4012/4012 [==============================] - 103s 26ms/step - loss: 7.1893 - accuracy: 0.0418
Epoch 6/10
4012/4012 [==============================] - 102s 26ms/step - loss: 7.1839 - accuracy: 0.0418
Epoch 7/10
4012/4012 [==============================] - 100s 25ms/step - loss: 7.1799 - accuracy: 0.0418
Epoch 8/10
4012/4012 [==============================] - 99s 25ms/step - loss: 7.1769 - accuracy: 0.0418
Epoch 9/10
4012/4012 [==============================] - 102s 25ms/step - loss: 7.1748 - accuracy: 0.0418
Epoch 10/10
4012/4012 [==============================] -

In [132]:
import numpy as np
text = 'what'

sequence = tokenizer.texts_to_sequences([text])
padded = pad_sequences(sequence, maxlen=MAX_LEN, padding='post')

np.argmax(model.predict(padded), axis=1)

1/1 [==============================] - 1s 612ms/step


array([1])

In [133]:
preds = model.predict(padded)
preds.argmax(axis=1)

1/1 [==============================] - 0s 23ms/step


array([1])

In [134]:
index2word.get(1)

'the'

In [1]:
embed_dim = 32
num_heads = 2
ff_dim = 32

In [ ]:
iputs = input(shape=(MAX_LEN,))
embedding_layer = TokenAndPositionEmbedding(MAX_LEN,vocab_size,embed_dim)
x = embedding_layer(input)
transformer_block = TransformerBlock(embed_dim,num_heads,ff_dim)
x = transformer_block(x)
x = GlobalAveragePooling1D(x)
x = Dropout(0.1)(x)
x = Dense(20,activation="relu")(x)
x  = Dropout(0.1)(x)
outputs = Dense(2,activation="softmax")(x)

model = Model(input=inputs,output = outputs)

In [ ]:
model.compile(
    optimizer = "adam",loss = "sparse_categorical_crossentropy",
    metrics = ['accuracy']
)